from pydantic import BaseModel, Field
from typing import List, Optional


class AttackHypothesis(BaseModel):
    """
    Rich attack hypothesis generated by the LLM.

    This is the internal contract of Member 1.
    Member 2 will primarily consume attack_type.
    """

    attack_id: str = Field(
        description="Unique identifier for this attack hypothesis"
    )

    attack_name: str = Field(
        description="Human-readable name of the attack"
    )

    attack_type: str = Field(
        description=(
            "Exact registered attack type when known. "
            "For the current system, use one of the 10 supported attack types."
        )
    )

    attack_category: str = Field(
        description="Category of the attack"
    )

    description: str = Field(
        description="Explanation of how the attack works"
    )

    genai_capability: str = Field(
        description="GenAI capability involved in the attack"
    )

    target: str = Field(
        description="Payment system, process, or entity targeted"
    )

    attack_vector: str = Field(
        description="Mechanism through which the attack is performed"
    )

    required_capabilities: List[str] = Field(
        description="Resources or capabilities required by the attacker"
    )

    potential_impact: str = Field(
        description="Potential financial, operational, or security impact"
    )

    severity_score: int = Field(
        ge=1,
        le=10,
        description="Severity score from 1 to 10"
    )

    feasibility_score: int = Field(
        ge=1,
        le=10,
        description="Feasibility score from 1 to 10"
    )

    novelty_score: int = Field(
        ge=1,
        le=10,
        description="Novelty score from 1 to 10"
    )

    risk_score: float = Field(
        ge=0,
        le=10,
        description="Overall risk score from 0 to 10"
    )

    attack_signals: List[str] = Field(
        description="Observable behavioral or transaction signals"
    )

    default_channel_bias: Optional[List[str]] = Field(
        default=None,
        description="Typical channels associated with this attack"
    )

    severity_weight: Optional[float] = Field(
        default=None,
        ge=0,
        le=1,
        description="Severity weight used by the transaction generator"
    )

    known_type: bool = Field(
        description=(
            "True when attack_type is one of the currently registered "
            "attack types; false for a novel attack"
        )
    )